[project]
name = "efficiency-calculator"
version = "0.0.1"
description = "A windmill efficiency calculator for the WiterOK website"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
  { name = "Ivan Krykun", email = "vanakrikun0@gmail.com" }
]

dependencies = [
  "requests>=2.31",
  "os>=1.0",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff",
]
